// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoqbMVGeU-0rkEZX0ujly1mHWDyws9cEk',
    appId: '1:543348323730:web:670588e01fbe719b10fd4b',
    messagingSenderId: '543348323730',
    projectId: 'sportify-v1-mobile-6',
    authDomain: 'sportify-v1-mobile-6.firebaseapp.com',
    storageBucket: 'sportify-v1-mobile-6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNOAJNxfxUzHZQCEg__9Ed-2susZJ0Lo',
    appId: '1:543348323730:android:ba1add9176758f9810fd4b',
    messagingSenderId: '543348323730',
    projectId: 'sportify-v1-mobile-6',
    storageBucket: 'sportify-v1-mobile-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmrDoGZfg-vZ2jhrHZuS0LICyzxui9eNo',
    appId: '1:543348323730:ios:cd68e4cc341afcb810fd4b',
    messagingSenderId: '543348323730',
    projectId: 'sportify-v1-mobile-6',
    storageBucket: 'sportify-v1-mobile-6.firebasestorage.app',
    iosBundleId: 'com.example.sportifyV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmrDoGZfg-vZ2jhrHZuS0LICyzxui9eNo',
    appId: '1:543348323730:ios:cd68e4cc341afcb810fd4b',
    messagingSenderId: '543348323730',
    projectId: 'sportify-v1-mobile-6',
    storageBucket: 'sportify-v1-mobile-6.firebasestorage.app',
    iosBundleId: 'com.example.sportifyV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoqbMVGeU-0rkEZX0ujly1mHWDyws9cEk',
    appId: '1:543348323730:web:d7d44010decf7e3f10fd4b',
    messagingSenderId: '543348323730',
    projectId: 'sportify-v1-mobile-6',
    authDomain: 'sportify-v1-mobile-6.firebaseapp.com',
    storageBucket: 'sportify-v1-mobile-6.firebasestorage.app',
  );
}
